// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQo35NeRLu9PVlqBmTM5VTwzodxUXeKz0',
    appId: '1:642806091331:web:ffe6bc7d46e642eab20ef6',
    messagingSenderId: '642806091331',
    projectId: 'unimarket-ueb-1',
    authDomain: 'unimarket-ueb-1.firebaseapp.com',
    storageBucket: 'unimarket-ueb-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKuUKprQxzwPCR3cPgBEv3-5-QbiCiDQE',
    appId: '1:642806091331:android:a38c8c9d78103c4ab20ef6',
    messagingSenderId: '642806091331',
    projectId: 'unimarket-ueb-1',
    storageBucket: 'unimarket-ueb-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0vAV4n4UgUGP3v4RPFDb2jJVvbImlFzA',
    appId: '1:642806091331:ios:2b4dbafb2ea0acbdb20ef6',
    messagingSenderId: '642806091331',
    projectId: 'unimarket-ueb-1',
    storageBucket: 'unimarket-ueb-1.firebasestorage.app',
    iosBundleId: 'com.example.unimarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0vAV4n4UgUGP3v4RPFDb2jJVvbImlFzA',
    appId: '1:642806091331:ios:2b4dbafb2ea0acbdb20ef6',
    messagingSenderId: '642806091331',
    projectId: 'unimarket-ueb-1',
    storageBucket: 'unimarket-ueb-1.firebasestorage.app',
    iosBundleId: 'com.example.unimarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQo35NeRLu9PVlqBmTM5VTwzodxUXeKz0',
    appId: '1:642806091331:web:ebab6f627eac2416b20ef6',
    messagingSenderId: '642806091331',
    projectId: 'unimarket-ueb-1',
    authDomain: 'unimarket-ueb-1.firebaseapp.com',
    storageBucket: 'unimarket-ueb-1.firebasestorage.app',
  );

}